// app/[locale]/layout.tsx

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string }; 
}) {
  return (
    <html lang={params.locale}>
      <body>{children}</body>
    </html>
  );
}
